<?php
declare(strict_types=1);
function check(bool $condition, string $message): void { if (!$condition) throw new RuntimeException($message); }
$page = file_get_contents(__DIR__ . '/../php/admin-editorial-topics.php');
$api = file_get_contents(__DIR__ . '/../php/admin-editorial-topics-api.php');
$js = file_get_contents(__DIR__ . '/../assets/js/admin-editorial-topics.js');
$css = file_get_contents(__DIR__ . '/../assets/css/admin.css');
$service = file_get_contents(__DIR__ . '/../php/generation-batch-service.php');
$filterState = file_get_contents(__DIR__ . '/../assets/js/topic-filter-state.js');
$panel = file_get_contents(__DIR__ . '/../assets/js/admin-panel.js');
check(strpos($page, 'topic-card-selector') < strpos($page, 'editorial-status'), 'Checkbox nie jest bezpośrednio przed badge’em.');
check(strpos($page, 'topic-bulk-toolbar') < strpos($page, 'topic-list-heading'), 'Toolbar zbiorczy ma być nad nagłówkiem listy.');
check(str_contains($page, 'aria-label="Przenieś temat do Kosza:') && str_contains($page, 'topic-trash'), 'Brak kontraktu kosza.');
foreach (['research','draft','quality','images','generate_all'] as $action) check(str_contains($page, 'value="'.$action.'"'), 'Brak akcji '.$action);
check(str_contains($page, 'toggle_automatic_dispatch') && str_contains($page, 'dispatcher_state'), 'Brak ręcznego przycisku pauza/play automatycznego dispatchera.');
check(str_contains($js, 'paused_by_operator') && str_contains($js, 'Wstrzymany — uruchom ręcznie'), 'UI nie pokazuje stanu wstrzymanego bez countdownu.');
check(str_contains($js, 'selected = new Set()') && str_contains($js, 'topic-select-visible') && str_contains($js, 'topic-select-top'), 'Brak selekcji zbiorczej.');
check(str_contains($page, 'topic-clear-selection') && str_contains($page, 'Zaznaczono:') && str_contains($page, 'data-selected="false"'), 'Brak jawnego, wspólnego stanu wyboru.');
check(str_contains($page, 'aria-describedby="topic-title-') && str_contains($page, 'topic-selected-badge'), 'Checkbox nie jest powiązany z tytułem lub brakuje tekstowego stanu karty.');
check(str_contains($js, "card.classList.toggle('is-selected'") && str_contains($js, "card.dataset.selected ="), 'Stan karty nie jest aktualizowany natychmiast.');
check(!str_contains($js, 'if (card.hidden) selected.delete'), 'Filtrowanie po cichu usuwa zaznaczenie.');
check(str_contains($js, 'hiddenSelected') && str_contains($js, 'ukrytych przez'), 'Liczba zaznaczonych, ale ukrytych tematów nie jest jawna.');
check(str_contains($css, 'width:44px') && str_contains($css, 'width:24px!important') && str_contains($css, '.topic-control-card.is-selected'), 'Checkbox nie ma wymaganego rozmiaru lub karta nie ma stanu zaznaczenia.');
check(str_contains($js, 'payload.skipped') && str_contains($service, "'skipped'"), 'Brak raportu pominięć dla mieszanego wyboru.');
check(str_contains($api, 'admin_valid_csrf') && str_contains($service, 'request_key') && str_contains($service, 'generation_batch_audit'), 'Brak zabezpieczeń kontraktu.');
check(str_contains($api, "\$action === 'pause_item'") && str_contains($api, 'generation_batch_pause_item') && str_contains($api, "\$action === 'resume_item'") && str_contains($api, 'resume_generation_batch_item'), 'Brak routingu API pauzy/wznowienia pojedynczego tematu.');
check(str_contains($page, 'topic-pause-item') && str_contains($page, 'topic-resume-item') && str_contains($page, 'Wstrzymaj generowanie tego tematu') && str_contains($page, 'Wznów generowanie tego tematu'), 'Brak dostępnych kontrolek pauzy/wznowienia przy karcie tematu.');
check(str_contains($js, "'pause_item'") && str_contains($js, "'resume_item'") && str_contains($js, '[data-pause-item], [data-resume-item]') && str_contains($js, 'generateAll.after(pauseButton)') && str_contains($js, 'pauseButton.after(resumeItemButton)') && str_contains($js, 'refresh();'), 'JS nie obsługuje dynamicznych kontrolek pauzy/wznowienia pojedynczego tematu.');
$sourceToolsPosition = strpos($page, 'topic-source-tools');
check(str_contains($page, 'Źródła i ręczne rozdzielanie') && $sourceToolsPosition !== false && !str_contains($page, 'merge_topics'), 'Panel źródeł nadal oferuje łączenie tematów.');
check(str_contains($page, 'form="topic-trash-bulk-form"') && !str_contains($page, 'topic-trash-bulk-check'), 'Zbiorczy Kosz nie korzysta ze wspólnego zaznaczenia.');
check(str_contains($js, 'trashHiddenIds') && str_contains($js, "window.confirm('Przenieść ' + selected.size"), 'Brak synchronizacji i potwierdzenia zbiorczego Kosza.');
check(str_contains($css, '.topic-trash-selected'), 'Brak kompaktowego Kosza w toolbarze.');
check(str_contains($css, '@media(max-width:900px)') && str_contains($css, '@media(max-width:520px)'), 'Brak breakpointów responsywnych.');
check(str_contains($js, "document.addEventListener('visibilitychange'") && str_contains($js, "window.addEventListener('online'"), 'Client does not resync after tab visibility or network recovery.');
check(str_contains($js, 'serverOffset = Date.parse(payload.server_time) - Date.now()') && str_contains($js, 'job.next_retry_at || job.available_at'), 'Countdown is not based on canonical backend time.');
check(str_contains($js, 'networkFailures++') && str_contains($js, 'Math.pow(2'), 'Network retry does not use controlled backoff.');
foreach (['W kolejce', 'Aktywne przetwarzanie', 'Limit API', 'Wymaga decyzji', 'Błąd ponawialny', 'Błąd trwały'] as $label) check(str_contains($js, $label), 'Missing state message: ' . $label);
check(str_contains($api, "'server_time' => gmdate('c')") && str_contains($service, "'next_retry_at' => \$availableAt"), 'API does not expose server and canonical resume time.');
check(!str_contains($service, "'Oczekiwanie na limit API ('"), 'SSR reason must not contain a second independent countdown.');
check(str_contains($page, 'if ($state[\'proposal_url\'])') && str_contains($page, 'Otwórz propozycję do przeglądu'), 'Topic card has no direct link to a reviewable draft.');
check(str_contains($page, 'return_topic_id') && str_contains($page, "'#topic-' . \$returnTopicId"), 'Akcje karty nie zachowują stabilnego anchoru tematu.');
check(str_contains($page, 'return_filter') && str_contains($page, 'http_build_query($returnQuery)'), 'Redirect po akcji nie zachowuje filtra listy.');
check(str_contains($page, 'topic-card-message') && str_contains($page, 'topic_message_topic_id'), 'Komunikaty akcji nie są przypisane do konkretnej karty tematu.');
check(str_contains($js, 'cardMessage(topicId') && !str_contains($js, 'live.focus()'), 'JavaScript nadal przenosi fokus do globalnego komunikatu.');
check(str_contains($page, 'topic-show-ready') && str_contains($page, 'topic-show-action') && str_contains($page, 'uwagi'), 'Brak filtrów gotowych i wymagających uwagi.');
check(str_contains($panel, 'requiresDocumentNavigation') && str_contains($panel, 'admin-editorial-topics'), 'Tematy nie wymuszają pełnej nawigacji zamiast nieinicjalizowanego soft-routera.');
check(str_contains($page, 'data-requires-action=') && str_contains($js, 'showReady.checked') && str_contains($js, 'showAction.checked') && str_contains($page, "!array_key_exists('show_action', \$_GET)"), 'Domyślnie aktywny filtr wymagających uwagi nie jest utrwalony.');
check(substr_count($page, 'id="topic-show-ready"') === 1 && substr_count($page, 'id="topic-show-action"') === 1, 'Filtry mają brakujące lub zduplikowane id.');
check(str_contains($page, 'for="topic-show-ready"') && str_contains($page, 'for="topic-show-action"'), 'Etykiety filtrów nie są jawnie połączone z checkboxami.');
check(str_contains($page, 'show_ready') && str_contains($page, 'return_show_ready') && str_contains($js, 'history.replaceState'), 'Stan filtrów nie jest utrwalany w URL i redirectach kart.');
check(str_contains($page, 'data-queue-state=') && str_contains($js, 'topicFilterState.matches') && str_contains($filterState, "queueState === 'ready'"), 'JS nie korzysta z backendowego queue_state.');
check(str_contains($page, 'generation_topic_queue_visible') && str_contains($page, '$visibleTopicCount'), 'Pierwszy render SSR nie stosuje wspólnej klasyfikacji kolejki.');
check(str_contains($js, 'data-nav-queue-count') && str_contains($js, 'topicFilterState.counts'), 'Polling nie aktualizuje liczników trzech kolejek.');
$nav = file_get_contents(dirname(__DIR__) . '/php/admin-nav.php');
$api = file_get_contents(dirname(__DIR__) . '/php/admin-editorial-topics-api.php');
check(str_contains($nav, 'generation_active_topic_queue_counts') && substr_count($nav, 'data-nav-queue-count=') === 2 && !str_contains($nav, 'admin-proposals.php?queue=action'), 'Nawigacja nadal pokazuje osobną stronę wymagających uwagi.');
check(str_contains($api, 'list_editorial_topics(1000, $filter)'), 'Polling nie pobiera tego samego zakresu tematów co SSR.');
check(str_contains($css, '.topic-filter-checkbox:checked') && str_contains($css, '.topic-filter-checkbox:focus-visible'), 'Checkboxy filtrów nie mają jednoznacznego checked/focus.');
check(str_contains($page, 'topic-card-heading') && str_contains($page, '<span>Zaznacz temat</span>'), 'Selektor karty nie ma osobnego układu checkbox + tekst.');
check(str_contains($css, '.topic-card-heading>h3') && str_contains($css, '.admin-preview-action{display:inline-flex'), 'Tytuł lub przycisk Podgląd nie mają poprawnego układu i centrowania.');
check(str_contains($css, '#topic-search') && str_contains($css, 'min-height:44px') && str_contains($css, 'label[for="topic-search"]'), 'Wyszukiwarka nie ma spójnej wysokości, typografii lub wyśrodkowanej etykiety.');
check(str_contains($css, '.topic-card-actions button:not(.topic-generate-all)') && str_contains($css, ':disabled'), 'Brak lokalnej hierarchii secondary/primary przycisków karty.');
check(str_contains($css, '.topic-control-card[hidden]{display:none!important}'), 'CSS nadpisuje atrybut hidden i pozostawia odfiltrowane karty na ekranie.');
check(str_contains($js, "'Grafiki: '") && str_contains($js, "' · wyszukiwanie zakończone'"), 'UI nadal myli ukończenie fazy images z pełnym coverage.');
echo "TOPIC_WORKFLOW_UI_SMOKE_OK\n";
