<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/php/admin-auth.php';
require_once dirname(__DIR__) . '/php/admin-database.php';
$items = [
    ['id'=>241,'title'=>'Nowy materiał nadprzewodzący działa w rekordowej temperaturze','status'=>'draft','score'=>94,'sources'=>'Nature, arXiv','days'=>1,'date'=>'2026-07-22 09:15:00','due'=>'2026-08-01 09:15:00','links'=>'3 wpisy RSS · 2 operacje · 1 research · 2 wersje'],
    ['id'=>238,'title'=>'Teleskop odsłania atmosferę odległej planety','status'=>'published','score'=>88,'sources'=>'NASA, Science','days'=>4,'date'=>'2026-07-25 11:40:00','due'=>'2026-08-04 11:40:00','links'=>'4 wpisy RSS · 5 operacji · 2 research · 3 wersje · publikacja chroniona'],
    ['id'=>226,'title'=>'Badacze mapują komunikację wielorybów','status'=>'review','score'=>79,'sources'=>'NOAA, Nature','days'=>8,'date'=>'2026-07-29 14:05:00','due'=>'2026-08-08 14:05:00','links'=>'2 wpisy RSS · 1 operacja · 1 research · 1 wersja'],
];
?><!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kosz tematów — visual QA</title><link rel="stylesheet" href="../assets/css/main.css"><link rel="stylesheet" href="../assets/css/admin.css"></head>
<body class="admin-page admin-page-topic-trash"><div id="wrapper"><main class="admin-main"><?php $adminActive='topic-trash'; require dirname(__DIR__) . '/php/admin-nav.php'; ?><div class="admin-context"><nav class="admin-breadcrumb"><a>Panel</a><span>/</span><span>Kosz tematów</span></nav></div><section class="post admin-card topic-trash-page"><header class="major admin-heading"><p class="admin-kicker">Retencja 10 dni</p><h1>Kosz tematów</h1><p>Tematy można przywrócić do dnia wskazanego na karcie. Trwałe usunięcie zachowuje publikacje, źródła, licencje i historię operacji.</p></header>
<form class="topic-trash-filters"><label>Szukaj <input type="search" placeholder="Tytuł lub źródło"></label><label>Status sprzed usunięcia <select><option>Wszystkie</option></select></label><label>Sortowanie <select><option>Najbliższy termin</option></select></label><button>Filtruj</button></form>
<form class="topic-trash-bulk"><strong>0 zaznaczonych</strong><button>Przywróć zaznaczone</button><label><input type="checkbox"> Potwierdzam nieodwracalną operację</label><label>Wpisz <code>USUŃ TRWALE</code> <input></label><button class="admin-danger-action">Usuń trwale zaznaczone</button></form><div class="topic-trash-list">
<?php foreach($items as $item): ?><article class="technical-source-card topic-trash-card"><input class="topic-trash-select" type="checkbox" aria-label="Wybierz temat"><div class="topic-trash-card__body"><header><div><span class="editorial-status">#<?php echo $item['id']; ?> · <?php echo $item['status']; ?></span><h2><?php echo $item['title']; ?></h2></div><strong class="topic-trash-deadline"><?php echo $item['days']; ?> dni do usunięcia</strong></header><p><strong>Score sprzed usunięcia: <?php echo $item['score']; ?>/100</strong> · źródła: <?php echo $item['sources']; ?></p><p>Przeniesiono: <?php echo $item['date']; ?> UTC przez admin. Termin: <?php echo $item['due']; ?> UTC.</p><p>Powiązania: <?php echo $item['links']; ?>.</p><div class="editorial-action-row"><button>Przywróć</button><details><summary>Usuń trwale teraz</summary></details></div></div></article><?php endforeach; ?>
</div></section><button class="admin-nav-backdrop"></button></main></div></body></html>
