<?php
$count = max(0, min(80, (int) ($_GET['count'] ?? 10)));
$states = ['research', 'draft', 'quality', 'ready', 'open'];
?><!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tematy — visual QA</title><link rel="stylesheet" href="../assets/css/main.css"><link rel="stylesheet" href="../assets/css/admin.css"></head>
<body class="admin-page admin-page-topics"><main class="admin-main"><section class="post admin-card technical-sources-page"><header class="major admin-heading"><p class="admin-kicker">Centrum generowania</p><h1>Tematy redakcyjne</h1><p>Wybieraj najwyżej punktowane tematy i prowadź je przez research, szkic, kontrolę jakości oraz legalne grafiki.</p></header>
<nav class="editorial-filters"><a class="is-active">Aktywne</a><a>Wszystkie</a><label>Szukaj <input type="search" placeholder="ID, tytuł lub źródło"></label><label>Stan <select><option>Do pracy</option></select></label></nav>
<form class="topic-bulk-toolbar"><div class="topic-bulk-select"><label><input type="checkbox"> Zaznacz wszystkie widoczne</label><button type="button">Zaznacz top 10</button><strong>0 zaznaczonych</strong></div><div class="topic-action-toolbar"><button disabled>Research</button><button disabled>Szkic</button><button disabled>Kontrola jakości</button><button disabled>Grafiki</button><button disabled class="topic-generate-all">Wygeneruj całość</button><button disabled class="topic-trash-selected admin-danger-action"><span aria-hidden="true">🗑</span><span>Do kosza</span></button><a class="topic-trash-link">Otwórz Kosz</a></div><p id="topic-bulk-scope">Wybierz tematy. Bezpieczny limit partii: 10.</p></form>
<div class="topic-list-heading"><h2>Tematy (<?php echo $count; ?>)</h2><span>Malejąco według punktacji</span></div><div class="technical-source-list topic-control-list">
<?php for ($i=0;$i<$count;$i++): $id=241-$i;$score=max(20,96-$i);$state=$states[$i%count($states)];$ready=$state==='ready'; ?>
<article class="technical-source-card topic-control-card<?php echo $ready?' is-ready':''; ?>"><header><div><div class="topic-card-selector"><input class="topic-checkbox" type="checkbox" aria-label="Zaznacz temat #<?php echo $id; ?>: <?php echo $i===0?'Nowy materiał nadprzewodzący działa w rekordowej temperaturze':'Temat redakcyjny '.$id; ?>"><span class="editorial-status"><?php echo 1+$i%4; ?> wpisów / <?php echo 1+$i%3; ?> źródeł</span><?php if($ready):?><span class="topic-ready-badge">Gotowe</span><?php endif;?></div><h3>#<?php echo $id; ?> — <?php echo $i===0?'Nowy materiał nadprzewodzący działa w rekordowej temperaturze':'Temat redakcyjny '.$id; ?></h3></div><a class="button admin-preview-action">Podgląd</a></header><p><strong>Wynik: <?php echo $score; ?>/100</strong> · ryzyko: niskie · automatyzacja: dozwolona</p><p>Nature, arXiv · status: draft</p>
<ol class="topic-workflow-path"><li class="<?php echo $state!=='open'?'is-done':''; ?>">Research <?php echo $state!=='open'?'✓':'—'; ?></li><li class="<?php echo in_array($state,['draft','quality','ready'])?'is-done':''; ?>">Szkic <?php echo in_array($state,['draft','quality','ready'])?'v2 ✓':'—'; ?></li><li class="<?php echo in_array($state,['quality','ready'])?'is-done':''; ?>">QC <?php echo in_array($state,['quality','ready'])?'✓':'—'; ?></li><li class="<?php echo $ready?'is-done':''; ?>">Grafiki <?php echo $ready?'✓':'—'; ?></li><li class="<?php echo $ready?'is-done':''; ?>">Gotowe <?php echo $ready?'✓':'—'; ?></li></ol>
<?php if(in_array($state,['research','draft','quality'])):?><div class="topic-job-status"><strong><?php echo $state; ?> · <?php echo $state==='research'?20:($state==='draft'?55:78); ?>%</strong><progress max="100" value="<?php echo $state==='research'?20:($state==='draft'?55:78); ?>"></progress><span>Worker #2 przetwarza etap.</span></div><?php endif;?>
<div class="topic-card-actions"><button>Research</button><button>Szkic</button><button>Kontrola jakości</button><button>Grafiki</button><button class="topic-generate-all">Wygeneruj całość</button></div><?php if($ready):?><a class="topic-proposal-link">Otwórz gotową propozycję →</a><?php endif;?><details><summary>Składowe punktacji i uzasadnienie</summary></details><details class="topic-source-tools"><summary>Źródła i ręczne rozdzielanie</summary><div class="topic-source-tools__content"><p>Lista źródeł.</p></div></details><button class="topic-trash" disabled aria-label="Przenieś temat do kosza">🗑</button></article>
<?php endfor; ?></div><?php if($count===0):?><p class="admin-notice">Brak tematów spełniających filtry.</p><?php endif;?></section></main></body></html>
